### PR TITLE
recruiting instructors/TA for Spanish workshops

### PR DESCRIPTION
**Pull request by raynamharris**

### CODE REVIEW

**Comment by raynamharris** [comment]
Once this is up, will send email to instructor lists including bayarea, davis, and seattle

**Comment by karenword** [comment]
OK so just discussed with @ctb and while we are confident about *space* for two Spanish workshops, we are not totally confident about filling 2 workshops with *learners.*  I think we may have discussed this, and it may be ok to run these on the small side, but should be clear
We discussed opening up one workshop and seeing how much interest we get, then going for a second if there's lots. However, with the content split, that wouldn't really work so well. So we could probably only do that if we didn't split the content.

Re instructor recruitment: Do we need 2 instructors for each workshop? Are these in addition to you and Tessa?

Re application: I have a different from for Carpentry Workshop Instructor/TAs (vs the ANGUS application which is currently linked). It's here: https://goo.gl/forms/3tHz3HDzmZTbvetx2

Re davis contacts -- I have previously invited our davis local instructors to help out with workshops (including Spanish) so this should be presented to them with that in mind. (If you want to join the davis_local Carpentries listserv to be able to send to them, you can do so here: https://groups.google.com/a/carpentries.org/forum/?hl=en#!forum/davis-local)

**Comment by raynamharris** [comment]
Got it re. space and interest. 

My Spanish is plummeting back towards no longer fluent, so I prefer to consider my self the workshop coordinator.  Last I checked with Tessa, she was uncertain as to her geographical situation in June. So, we need at least two. perhaps two more. Maybe this is a reason enough to just go for 1 workshop...

I will update the form with a commit.

Nice! The Davis, Berkeley, and seattle groups are on my list of lists to hit

**Comment by raynamharris** [comment]
Thanks @karenword

**Pull request merged**
