### PR TITLE
rename to CarpentryConnect Davis

### PR DESCRIPTION
**Pull request by raynamharris**
update nearly all mentions of CarpentryCon to CarpentryConnect  https://github.com/dib-lab/dibsi/pull/26

### CODE REVIEW

**Comment by ctb** [comment]
uh why a separate pull request than #26? :)

**Comment by raynamharris** [comment]
I know. I just realized.

**Comment by ctb** [comment]
k - happy to merge yours, just wondering :)

**Comment by raynamharris** [comment]
i have a plan

**Comment by ctb** [comment]
oh noes

**Pull request closed without merging**
